# Generated by Django 5.1.6 on 2025-02-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("Employee_no", models.CharField(max_length=50)),
                ("Section", models.CharField(max_length=50)),
            ],
        ),
    ]
