# Generated by Django 5.1.6 on 2025-02-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.CharField(max_length=100)),
                ("Part_no", models.CharField(max_length=100)),
                ("process", models.CharField(max_length=100)),
                ("customer", models.CharField(max_length=40)),
                ("product_family", models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Employee_id", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Worker_out",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_status", models.CharField(max_length=20)),
                ("Out_data", models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
