# Generated by Django 5.1.6 on 2025-02-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_products_worker_worker_out_delete_employee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="Part_no",
            new_name="part_no",
        ),
        migrations.RenameField(
            model_name="worker",
            old_name="Employee_id",
            new_name="employee_id",
        ),
        migrations.RenameField(
            model_name="worker_out",
            old_name="Out_data",
            new_name="output_data",
        ),
    ]
