# Generated by Django 5.1.6 on 2025-02-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_part_no_products_part_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="id",
        ),
        migrations.AlterField(
            model_name="worker",
            name="employee_id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
